config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :cuisines, only: [:create, :edit, :new, :show, :update]
  resources :recipes, only: [:create, :edit, :new, :show, :update]
  resources :recipe_types, only: [:create, :edit, :new, :show, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes

  validates :name, presence: { message: 'Você deve preencher o nome da cozinha' }
  validates :name, uniqueness: { message: 'Essa cozinha já existe' }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :cuisine
  belongs_to :recipe_type

  validates :title, :difficulty, :cook_time, :ingredients, :method, presence:  { message: 'Você deve preencher todos os dados da receita' }
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes

  validates :name, presence: { message: 'Você deve preencher o nome do tipo de receita' }
  validates :name, uniqueness: { message: 'Esse tipo de receita já existe' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def create
    @cuisine = Cuisine.new create_params

    if @cuisine.save
      redirect_to cuisine_path @cuisine
    else
      @cuisine
      render :new
    end
  end

  def edit
    @cuisine = Cuisine.find_by(id: params[:id])
  end

  def new
    @cuisine = Cuisine.new
  end

  def show
    @cuisine = Cuisine.find params[:id]

    unless @cuisine.recipes.any?
      msg = 'Nenhuma receita encontrada para este tipo de cozinha'
      flash[:notice] = msg
    end
  end

  def update
    @cuisine = Cuisine.find_by(id: params[:id])
    if @cuisine.update(create_params)
      redirect_to cuisine_path @cuisine
    else
      @cuisines
      render :edit
    end
  end

  private

  def create_params
    params.require(:cuisine).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
    @recipes = Recipe.all
  end
end

app/controllers/recipe_types_controller.rb
# frozen_string_literal: true

class RecipeTypesController < ApplicationController
  def create
    @recipe_type = RecipeType.new(create_params)

    if @recipe_type.save
      redirect_to recipe_type_path @recipe_type
    else
      @recipe_type
      render :new
    end
  end

  def edit
    @recipe_type = RecipeType.find_by(id: params[:id])
  end

  def new
    @recipe_type = RecipeType.new
  end

  def show
    @recipe_type = RecipeType.find params[:id]

    if @recipe_type.recipes.empty?
      msg = 'Nenhuma receita encontrada para este tipo de receita'
      flash[:notice] = msg
    end
  end

  def update
    @recipe_type = RecipeType.find_by(id: params[:id])

    if @recipe_type.update(create_params)
      redirect_to recipe_type_path @recipe_type
    else
      @recipe_type
      render :edit
    end
  end

  private

  def create_params
    params.require(:recipe_type).permit(:name)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def create
    @recipe = Recipe.new create_params

    if @recipe.save
      redirect_to recipe_path @recipe
    else
      @recipe
      @cuisines = Cuisine.all
      @recipe_types = RecipeType.all
      render :new
    end
  end

  def edit
    @recipe = Recipe.find params[:id]
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
  end

  def new
    @recipe = Recipe.new
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
  end

  def show
    @recipe = Recipe.find params[:id]
  end

  def update
    @recipe = Recipe.find_by(id: params[:id])
    if @recipe.update(create_params)
      redirect_to recipe_path @recipe
    else
      @recipe
      @cuisines = Cuisine.all
      @recipe_types = RecipeType.all

      render :edit
    end
  end

  private
    # Using a private method to encapsulate the permissible parameters
    # is just a good pattern since you'll be able to reuse the same
    # permit list between create and update. Also, you can specialize
    # this method with per-user checking of permissible attributes.
    def create_params
      params.require(:recipe).permit(:title, :recipe_type_id, :cuisine_id,
        :difficulty, :cook_time, :ingredients, :method)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuisines/_form.html.erb
<%= render partial: 'shared/model_errors', locals: { model: @cuisine } %>

<%= form_for @cuisine do |f| %>
  <div class=''>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %><br>
  </div>
  <p><%= f.submit label_button %></p>
<% end %>

app/views/cuisines/edit.html.erb
<h1>Edição de cozinha</h1>

<%= render partial: 'form', locals: { label_button: 'Editar' } %>

<div class=''>
  <%= link_to 'Voltar', @cuisine %>
</div>

app/views/cuisines/new.html.erb
<h1>Cadastro de cozinhas</h1>

<%= render partial: 'form', locals: { label_button: 'Enviar' } %>

<div class=''>
  <p><%= link_to 'Voltar', root_path %></p>
</div>

app/views/cuisines/show.html.erb
<h1><%= @cuisine.name %></h1>

<% @cuisine.recipes.each do |recipe| %>
  <h1><%= recipe.title %></h1>
  <h3>Detalhes</h3>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time %> minutos</li>
  </ul>
  <h3>Ingredientes</h3>
  <ul>
    <li><%= recipe.ingredients %></li>
  </ul>
  <h3>Como Preparar</h3>
  <ul>
    <li><%= recipe.method %></li>
  </ul>
<% end %>

<div class="">
  <%= link_to 'Voltar', root_path %>
</div>

<div class="">
  <%= link_to 'Editar', edit_cuisine_path(@cuisine) %>
</div>

app/views/home/index.html.erb
<h1>CookBook</h1>
<p>Bem-vindo ao maior livro de receitas online</p>
<!-- TODO: label para dividir a lista de receitas, das cozinhas e tipos de receitas -->
<% @recipes.each do |recipe| %>
  <h1><%= link_to recipe.title, recipe_path(recipe) %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time %> minutos</li>
  </ul>
<% end %>

<% @cuisines.each do |cuisine| %>
  <h1><%= link_to cuisine.name, cuisine_path(cuisine) %></h1>
<% end %>

<% @recipe_types.each do |recipe_type| %>
  <h1><%= link_to recipe_type.name, recipe_type_path(recipe_type) %></h1>
<% end %>

<div class=''>
  <p>
    <%= link_to 'Enviar uma receita', new_recipe_path %>
  </p>
</div>

<div class=''>
  <p>
    <%= link_to 'Cadastrar cozinha', new_cuisine_path %>
  </p>
</div>

<div class=''>
  <p>
    <%= link_to 'Cadastrar tipo de receita', new_recipe_type_path %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/recipe_types/_form.html.erb
<%= render partial: 'shared/model_errors', locals: { model: @recipe_type } %>

<%= form_for @recipe_type do |f| %>
  <div class=''>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>
  <p><%= f.submit label_button %></p>
<% end %>

app/views/recipe_types/edit.html.erb
<h1>Edição de tipo de receita</h1>

<div class=''>
  <%= render partial: 'form', locals: { label_button: 'Editar' } %>
</div>

<div class=''>
  <%= link_to 'Voltar', recipe_type_path(@recipe_type) %>
</div>

app/views/recipe_types/new.html.erb
<h1>Cadastro de tipo de receita</h1>

<div class=''>
  <%= render partial: 'form', locals: { label_button: 'Enviar' } %>
</div>

<div class=''>
  <%= link_to 'Voltar', root_path %>
</div>

app/views/recipe_types/show.html.erb
<h1><%= @recipe_type.name %></h1>

<% @recipe_type.recipes.each do |recipe| %>
  <h1><%= recipe.title %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time %> minutos</li>
  </ul>
<% end %>

<div class="">
  <%= link_to 'Voltar', root_path %>
</div>

<div class="">
  <%= link_to 'Editar', edit_recipe_type_path(@recipe_type) %>
</div>

app/views/recipes/_form.html.erb
<%= render partial: 'shared/model_errors', locals: { model: @recipe } %>

<%= form_for @recipe do |f| %>
  <p>
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title %><br>
  </p>
  <p>
    <%= f.label :recipe_type_id, 'Tipo da Receita' %>
    <%= f.collection_select(:recipe_type_id, @recipe_types, :id, :name) %><br>
  </p>
  <p>
    <%= f.label :cuisine_id, 'Cozinha' %>
    <%= f.collection_select(:cuisine_id, @cuisines, :id, :name) %>
  </p>
  <p>
    <%= f.label :difficulty, 'Dificuldade' %>
    <%= f.text_field :difficulty %><br>
  </p>
  <p>
    <%= f.label :cook_time, 'Tempo de Preparo' %>
    <%= f.text_field :cook_time %><br>
  </p>
  <p>
    <%= f.label :ingredients, 'Ingredientes' %>
    <%= f.text_field :ingredients %><br>
  </p>
  <p>
    <%= f.label :method, 'Como Preparar' %>
    <%= f.text_field :method %><br>
  </p>
  <%= f.submit label_button %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edição de receitas</h1>

<div class=''>
  <%= render partial: 'form', locals: { label_button: 'Editar' } %>
</div>

<div class=''>
  <p><%= link_to 'Voltar', root_path %></p>
</div>

app/views/recipes/new.html.erb
<h1>Cadastro de receitas</h1>

<div class=''>
  <%= render partial: 'form', locals: { label_button: 'Enviar' } %>
</div>

<div class=''>
  <p><%= link_to 'Voltar', root_path %></p>
</div>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>

<h3>Detalhes</h3>

<ul>
  <li><%= @recipe.recipe_type.name %></li>
  <li><%= @recipe.cuisine.name %></li>
  <li><%= @recipe.difficulty %></li>
  <li><%= @recipe.cook_time %> minutos</li>
</ul>

<h3>Ingredientes</h3>

<ul>
  <li><%= @recipe.ingredients %></li>
</ul>

<h3>Como Preparar</h3>

<ul>
  <li><%= @recipe.method %></li>
</ul>

<div class="">
  <%= link_to 'Voltar', root_path %>
</div>

<div class="">
  <%= link_to 'Editar', edit_recipe_path %>
</div>

app/views/shared/_flash_messages.html.erb
<%= flash[:alert] %>
<%= flash[:notice] %>

app/views/shared/_model_errors.html.erb
<% model.errors.full_messages.each do |message| %>
  <%= message %>
<% end %>